[build]
  command = "echo 'No build command required.'"
  publish = "."

[[redirects]]
  from = "/xblog"
  to = "http://ui.app.linkpc.net/xblog"
  host = "nlf01.p.dnsabr.com"
  status = 200
  force = true
