[build]
  functions = "netlify/edge-functions"

[functions]
  directory = "netlify/edge-functions"
  node_bundler = "esbuild" # 使用 esbuild 打包
  esmodules = true # 启用 ES 模块

[functions."proxy"] # 你的函数名称
  included_files = ["./**"] #或者具体的文件
  node_version = "18.18.0"  # 或者其他支持的Node.js版本
