[build]
  command = "echo 'No build command required.'"
  publish = "."

[[redirects]]
  from = "/*"
  to = "http://129.146.244.132:8085/:splat"
  host = "nlf01.p.dnsabr.com"
  status = 200
  force = true
