[build]
  command = "echo 'No build command required.'"
  publish = "."

[[redirects]]
  from = "/*"
  to = "http://ui.app.linkpc.net:30520/:splat"
  host = "nlf01.p.dnsabr.com"
  status = 200
  force = true
