[build]
  command = "echo 'No build command required.'"
  publish = "."

[[redirects]]
  from = "/wsblog"
  to = "http://ui.app.linkpc.net:30520/wsblog"
  host = "nlf01.p.dnsabr.com"
  status = 200
  force = true
